service: scapper

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-plugin-existing-s3

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-2

functions:
  scrap:
    handler: src/handler.scrap
    events:
      - schedule: cron(0 1-5 * * ? *)
  updateLatests:
    handler: src/handler.updateLatest
    events:
      - existingS3:
          bucket: scrapper-images
          events:
            - s3:ObjectCreated:*
custom:
  dotenv:
    path: ./.env.local
    include:
      - USERNAME
      - PASSWORD
      - AWS_USER_KEY
      - AWS_USER_SECRET

iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - 's3:PutBucketNotification'
    Resource:
      Fn::Join:
        - ''
        - - 'arn:aws:s3:::BUCKET_NAME or *'
